name: Release Node.js app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: express-app
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
